[*]
; offline = on
flash-attn = on
cache-type-k = q8_0
cache-type-v = q8_0
n-gpu-layers = all
; Concurrency
kv-unified = on
batch-size = 16384
ubatch-size = 1024
parallel = 8

[ThinkingCap-Qwen3.6-27B-MTP]
hf-repo = bottlecapai/ThinkingCap-Qwen3.6-27B-GGUF:Q4_K_M
spec-type = draft-mtp
spec-draft-n-max = 3

[ThinkingCap-Qwen3.6-27B]
hf-repo = bottlecapai/ThinkingCap-Qwen3.6-27B-GGUF:Q4_K_M

[Qwen3.6-35B-A3B-MTP]
hf-repo = unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q4_K_XL
spec-type = draft-mtp
spec-draft-n-max = 3

[Qwen3.6-35B-A3B]
hf-repo = unsloth/Qwen3.6-35B-A3B-GGUF:UD-Q4_K_XL

[Qwen3.6-27B-MTP]
hf-repo = unsloth/Qwen3.6-27B-MTP-GGUF:UD-Q4_K_XL
spec-type = draft-mtp
spec-draft-n-max = 3

[Qwen3.6-27B]
hf-repo = unsloth/Qwen3.6-27B-GGUF:UD-Q4_K_XL

[gemma-4-31B]
hf-repo = unsloth/gemma-4-31B-it-GGUF:UD-Q4_K_XL

[GLM-4.7-Flash]
hf-repo = unsloth/GLM-4.7-Flash-GGUF:UD-Q4_K_XL

[DeepSeek-R1-Distill-Qwen-32B]
hf-repo = unsloth/DeepSeek-R1-Distill-Qwen-32B-GGUF:Q4_K_M
