[*]
flash-attn = on
ctx-size = 32768
cache-type-k = q8_0
cache-type-v = q8_0

[unsloth/gemma-4-E4B-it-qat-GGUF:UD-Q4_K_XL]
hf = unsloth/gemma-4-E4B-it-qat-GGUF:UD-Q4_K_XL
ctx-size = 65536

[unsloth/Qwen3-235B-A22B-Instruct-2507-GGUF:UD-Q4_K_XL]
# 1-1.4 t/s
hf = unsloth/Qwen3-235B-A22B-Instruct-2507-GGUF:UD-Q4_K_XL
ctx-size = 4096
n-gpu-layers = 999
n-cpu-moe = 85
threads = 32
threads-batch = 32